title: liberation-system
description: Enterprise-grade solution with dark neon theme
url: "https://tiaastor.github.io"
baseurl: "/liberation-system"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
author: Tiation
github_username: tiaastor
