global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Liberation System application
  - job_name: 'liberation-system'
    static_configs:
      - targets: ['liberation-system:8000']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # PostgreSQL database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node exporter (if added later)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
