apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesh-network
  labels:
    app: mesh-network
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mesh-network
  template:
    metadata:
      labels:
        app: mesh-network
    spec:
      containers:
      - name: mesh-network
        image: mesh-network:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
